// Generated by Wrangler by running `wrangler types`

interface Env {
	BOT_TOKEN_DEV: string;
	BOT_TOKEN: string;
	BOT_INFO: string;
	NODE_ENV: string;
	GROQ_API_KEY: string;
	WALLET_MNEMONIC: string;
}
